### ISSUE TITLE
Past-expiry records cause runtime errors in express-brute 1.0.1

### ISSUE THREAD

**Issue by brettimus** [maddy2get/express-brute-sequelize#11]
This is the offending code in this library, comment is mine

```coffeescript
  get:(key, callback) ->
    _id = @options.prefix+key
    @_table.find(where:{_id:_id})
    .then (doc) =>
      ###
       `destroy` will return 1 from the promise when the record existed
      ###
      return @_table.destroy({where:{"_id":_id}}) if doc && new Date(doc.expires).getTime() < new Date().getTime()
      return Promise.resolve(count:doc.count,lastRequest:new Date(doc.lastRequest),firstRequest:new Date(doc.firstRequest)) if doc
      Promise.resolve()
    .then (data)->
      data = undefined if !data
      typeof callback == 'function' && callback(null,data)
      return null
    .catch (err) ->
      typeof callback == 'function' && callback(err)
      return null
```

When `doc.expires` is earlier than the current time, there's a call to `destroy`. If the record exists in the database, Sequelize resolved the promise with a `1`.

That means the callback is getting called with `1`.

In the express-brute library, [a truthiness check]( https://github.com/AdamPflug/express-brute/blob/v1.0.1/index.js#L98) is run against the return value of `get` to determine whether or not to update the lastRequest, etc.

This truthiness check assumes it's getting an object with the expected brute-record properties. [Line 100](https://github.com/AdamPflug/express-brute/blob/v1.0.1/index.js#L100) thus calls `getTime` on undefined and everything freaks out.

This is a one-line fix, I'll open a PR shortly

**Comment by jeremiepape** [comment]
Hi,
Could be nice to have a new version with this commit.
Thanks

**Comment by brettimus** [comment]
> Hi,
> Could be nice to have a new version with this commit.
> Thanks

Agreed!
