### ISSUE TITLE
sequelize deprecated Model.find

### ISSUE THREAD

**Issue by jeremiepape** [maddy2get/express-brute-sequelize#13]
Hi,
Just a warning with "_sequelize deprecated Model.find has been deprecated, please use Model.findOne instead_".

In /node_modules/express-brute-sequelize/index.js, line 58 and 93 : 
`return this._table.find({`
Replace by:
`return this._table.findOne({`

Thanks.

**Comment by maddy2get** [comment]
Fixed. Updated NPM as well.
