### ISSUE TITLE
Old version of Sequelize

### ISSUE THREAD

**Issue by AmitGoelNYC** [maddy2get/express-brute-sequelize#6]
Can you update the sequelize version in package.json to use a more recent version?

**Comment by crisward** [comment]
I've done a pull request which includes this and other updates.
https://github.com/maddy2get/express-brute-sequelize/pull/5

I'll wait a little longer then push my own version to npm.

**Comment by maddy2get** [comment]
Sorry about the delay guys. I have merged changes from @crisward. Let me know if any issues.
